:- dynamic java_call/2.
java_call(get_op_from_id,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/statespace/GetOpFromId.java").
java_call(list_all_eclipse_preferences,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetDefaultPreferencesCommand.java").
java_call(get_error_messages,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetErrorsCommand.java").
java_call(evaluate_formula_typecheck,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/FormulaTypecheckCommand.java").
java_call(get_machine_formulas,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetMachineStructureCommand.java").
java_call(load_cspm_spec_from_cspm_file,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/LoadCSPCommand.java").
java_call(start_animation,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/StartAnimationCommand.java").
java_call(load_xtl_spec_from_prolog_file,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/LoadXTLCommand.java").
java_call(activate_plugin,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/ActivateUnitPluginCommand.java").
java_call(load_classical_b_from_list_of_facts,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/LoadRulesProjectCommand.java").
java_call(evaluate_formula,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/EvaluateFormulaCommand.java").
java_call(get_animation_image_matrix_for_state,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetAnimationMatrixForStateCommand.java").
java_call(evaluate_formulas,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/EvaluateFormulasCommand.java").
java_call(compute_coverage,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/ComputeCoverageCommand.java").
java_call(get_version,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetVersionCommand.java").
java_call(get_possible_completions,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/CompleteIdentifierCommand.java").
java_call(get_transition_diagram,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetTransitionDiagramCommand.java").
java_call(prob2_execute_custom_operations,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetOperationByPredicateCommand.java").
java_call(get_machine_identifiers,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetMachineIdentifiersCommand.java").
java_call(get_animation_image_list,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetImagesForMachineCommand.java").
java_call(write_dotty_transition_diagram,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetDottyForTransitionDiagramCmd.java").
java_call(load_alloy_spec_from_term,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/LoadAlloyTermCommand.java").
java_call(es_copy_from_statespace,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/EvalstoreCreateByStateCommand.java").
java_call(op_timeout_occurred,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetOperationsWithTimeout.java").
java_call(deserialize,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/DeserializeStateCommand.java").
java_call(do_modelchecking,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/ModelCheckingStepCommand.java").
java_call(call_dot_command_and_dot_in_state,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetSvgForVisualizationCommand.java").
java_call(before_after_predicate,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/BeforeAfterPredicateCommand.java").
java_call(get_error_messages_with_span_info,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetErrorItemsCommand.java").
java_call(expand_formula,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/ExpandFormulaCommand.java").
java_call(set_eclipse_preference,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/SetPreferenceCommand.java").
java_call(list_current_eclipse_preferences,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetCurrentPreferencesCommand.java").
java_call(pretty_print_predicate,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/PrettyPrintFormulaCommand.java").
java_call(get_primed_predicate,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/PrimePredicateCommand.java").
java_call(call_table_command_in_state,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetTableForVisualizationCommand.java").
java_call(es_eval,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/EvalstoreEvalCommand.java").
java_call(get_weakest_precondition,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/WeakestPreconditionCommand.java").
java_call(prob2_redundant_invariants,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetRedundantInvariantsCommand.java").
java_call(get_pretty_print,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetInternalRepresentationPrettyPrintCommand.java").
java_call(cbc_solve_with_opts,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/CbcSolveCommand.java").
java_call(filter_states_for_predicate,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/FilterStatesForPredicateCommand.java").
java_call(serialize,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/SerializeStateCommand.java").
java_call(get_plugin_output,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetPluginResultCommand.java").
java_call(compute_efficient_statespace_stats,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/ComputeStateSpaceStatsCommand.java").
java_call(get_animation_image_matrix_for_state,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetImagesForStateCommand.java").
java_call(get_machine_files,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetAllUsedFilenamesCommand.java").
java_call(get_dot_commands_in_state,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetAllDotCommands.java").
java_call(insert_formula_for_expansion,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/InsertFormulaForVisualizationCommand.java").
java_call(call_dot_command_in_state,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetDotForVisualizationCommand.java").
java_call(check_csp_assertions,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/CSPAssertionsCommand.java").
java_call(state_property,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/CheckBooleanPropertyCommand.java").
java_call(find_state_for_predicate,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/FindStateCommand.java").
java_call(prob2_invariant_check,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/ConstraintBasedInvariantCheckCommand.java").
java_call(register_prob2_formula,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/RegisterFormulaCommand.java").
java_call(load_classical_b_from_list_of_facts,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/LoadBProjectCommand.java").
java_call(get_states_for_predicate,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetStatesFromPredicate.java").
java_call(set_goal_for_model_checking,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/SetBGoalCommand.java").
java_call(evaluate_registered_formulas,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/EvaluateRegisteredFormulasCommand.java").
java_call(load_event_b_project,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/LoadEventBProjectCommand.java").
java_call(generate_trace_until_condition_fulfilled,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/ExecuteUntilCommand.java").
java_call(unregister_prob2_formula,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/UnregisterFormulaCommand.java").
java_call(prob2_construct_trace,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/ConstructTraceCommand.java").
java_call(get_table_commands_in_state,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetAllTableCommands.java").
java_call(find_trace_to_node,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetShortestTraceCommand.java").
java_call(get_unsat_core_with_fixed_conjuncts,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/UnsatRegularCoreCommand.java").
java_call(write_dot_for_state_viz,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetDotForStateVizCmd.java").
java_call(get_minimum_unsat_core_with_fixed_conjuncts,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/UnsatMinimalCoreCommand.java").
java_call(prob2_deadlock_freedom_check,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/ConstraintBasedDeadlockCheckCommand.java").
java_call(compute_operations_for_state,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetEnabledOperationsCommand.java").
java_call(get_b_state,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetBStateCommand.java").
java_call(get_eclipse_preference,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetPreferenceCommand.java").
java_call(write_dotty_signature_merge,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetDottyForSigMergeCmd.java").
java_call(get_state_errors,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetStateBasedErrorsCommand.java").
java_call(get_react_to_item_right_click_options_for_state,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetRightClickOptionsForStateVisualizationCommand.java").
java_call(get_prob_total_number_of_errors,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetTotalNumberOfErrorsCommand.java").
java_call(react_to_item_right_click_option_for_state,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/ExecuteRightClickCommand.java").
java_call(prob2_do_ltl_modelcheck,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/LtlCheckingCommand.java").
java_call(get_enable_matrix,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetEnableMatrixCommand.java").
java_call(get_machine_operation_infos,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/GetMachineOperationInfos.java").
java_call(find_trace_from_node_to_node,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/FindTraceBetweenNodesCommand.java").
java_call(execute_model,"/Users/leuschel/git_root/JAVAPROB/java_prob2/de.prob2.kernel/src/main/java/de/prob/animator/command/ExecuteModelCommand.java").
