/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl:12: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl:90: ast_inspector:tcltk_get_node_info
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:22: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:46: tcltk_model_check
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:54: tcltk_goto_an_invariant_violation
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:155: system:environ
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:202: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:22: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:86: tcltk_bv_get_tops
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:125: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:133: "tcltk_bv_show_formula_as_dot_graph
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:142: "tcltk_bv_show_formula_as_dot_tree
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:152: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:160: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:162: tcltk_bv_get_unlimited_value
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:173: bv_show_formula_origin
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:234: "tcltk_bv_get_values
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:253: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:491: "current_expression
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:494: "bvisual2:bv_print_to_file
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:503: "current_expression
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:505: "bvisual2:bv_write_all_variables_and_constants
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:540: bv_formula_description
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:549: bv_is_typed_formula
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:550: bv_is_typed_predicate
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:559: bv_is_typed_identifier
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:658: "bvisual2:tcltk_register_new_user_formula
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:49: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:51: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:65: version:version
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:68: prolog_flag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:71: version:revision
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:73: version:lastchangeddate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:243: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:259: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:283: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:285: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:295: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:295: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:310: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:349: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:350: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:572: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:875: self_checks_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:881: self_checks_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:907: debug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:908: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:910: compile_time_flags:compile_time_flag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:933: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:939: (nl
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:944: state_space_initialise_with_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1013: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1025: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1029: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1054: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1057: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1060: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1063: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1093: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1098: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1170: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1179: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1192: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1196: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1207: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1211: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1212: test_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1217: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1228: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1230: error_or_warning_occured
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1257: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1304: "tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1306: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1343: "tcltk_show_expression_as_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1375: "tcltk_eval_as_table
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1376: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1434: "tcltk_explore_csp_process
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1437: get_csp_process_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1441: "tcltk_visualize_csp_process
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1450: "tcltk_visualize_csp_process
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1469: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1476: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1525: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1527: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1548: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1566: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1818: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1819: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1826: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2002: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2010: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2013: b_top_level_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2013: animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2019: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2053: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2070: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2092: tcltk_has_eventtrace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2106: tcltk_show_eventtrace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2118: tcltk_get_detailed_state_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2124: can_generate_dot_from_last_state_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2151: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2157: "eclipse_interface:ops_user_interrupt_occured
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2170: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2179: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2186: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2189: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2192: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2210: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2213: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2222: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2224: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2232: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2288: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2299: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2311: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2314: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2508: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2524: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2544: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2546: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2548: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2549: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2730: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2733: "animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2871: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3195: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3197: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3629: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3637: parsercall:check_java_version
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3639: parsercall:get_version_from_parser
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3657: perform_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3670: perform_verbose_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3683: get_module_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3686: perform_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3748: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3751: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3831: preferences:add_recent_document
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3845: "unset_tcltk_cspm_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3888: tcltk_load_packaged_eventb_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3894: bmachine:b_show_machine_representation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3949: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3955: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3958: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3962: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3966: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3969: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3972: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3975: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3983: tcltk_get_command_line_file_to_open
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3990: tcltk_get_command_line_tcltk_commands
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4009: tcltk_open_xtl_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4032: tcltk_open_alloy_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4173: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4193: tcltk_open_z_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4215: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4243: eclipse_interface:load_prob_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4244: tcltk_open_b_file_for_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4247: set_animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4306: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4307: "tools:platform_is_64_bit
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4357: tcltk_open_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4373: "set_tcltk_cspm_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4384: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4462: tcltk_add_csp_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4514: tcltk_open_b_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4678: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4680: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4714: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4740: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4761: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4789: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4793: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4798: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4801: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4807: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4812: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4816: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4824: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4837: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4841: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4847: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4852: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4860: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4864: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4874: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4880: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4888: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4902: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4919: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4922: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4926: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4931: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4936: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4940: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4944: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4948: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4958: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4961: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4965: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4969: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4973: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4984: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4987: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4991: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4995: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5006: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5009: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5014: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5018: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5023: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5027: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5031: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5040: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5043: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5048: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5054: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5060: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5064: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5069: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5080: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5102: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5139: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5140: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5143: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5146: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5149: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5153: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5156: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5159: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5162: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5198: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5234: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5236: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5248: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5258: "b_show_history:write_values_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5287: preferences:add_recent_document
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5391: tcltk_prepare_for_reload
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5449: tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5460: tcltk_random_perform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5465: tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5541: tcltk_random_perform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5544: tcltk_current_state_invariant_violated
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5553: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5581: tcltk_execute_until
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5601: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5602: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5615: "tcltk_execute_model
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5643: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5698: cli_prefs_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5699: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5701: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5704: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5710: tcltk_load_commandline_prefs_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5713: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5714: file_systems:file_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5715: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5717: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5837: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5850: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5852: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5874: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5877: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5959: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5965: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5980: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5981: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5987: preference_default_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5989: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5994: preference_default_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5996: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6007: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6007: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6008: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6015: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6024: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6032: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6134: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6138: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6142: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6179: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6180: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6184: model_checking_is_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6246: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6247: tcltk_unique_top_level_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6252: current_state_corresponds_to_setup_constants_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6325: "
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6351: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6351: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6357: b_get_machine_operation_parameter_names
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6360: b_get_operation_non_det_modifies
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6368: "tcltk_add_user_executed_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6455: query does not fail 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6456: interruptable_call(
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6467: query does not fail 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6468: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6469: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6471: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6525: interruptable_call(tcltk_debug_properties_or_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6563: tcltk_analyse_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6565: "register_conjunct_register_error_span
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6582: tcltk_state_exists_with_invariant_violated
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6601: "reset_conjunct_error_hook
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6614: b_reset_machine_goal_from_DEFINITIONS
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6639: tcltk_show_current_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6653: tcltk_clear_state_space_and_refocus_to_current_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6660: preferences:get_non_default_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6820: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6824: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6833: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6841: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6842: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6850: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6893: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6895: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6900: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6916: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6921: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6949: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6952: parsercall:ensure_console_parser_launched
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7095: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7167: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7174: last_expression_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7182: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7204: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7213: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7222: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7242: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7328: tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7334: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7337: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7356: "interruptable_tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7362: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7371: "b_simplifier: tcltk_simplify_b_predicate_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7374: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7392: get_error_positions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7399: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7425: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7561: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7562: popup
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7570: bmachine:tcltk_get_specialized_invariants_for_ops
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7576: b_read_write_info:tcltk_get_guards_for_ops
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7582: b_read_write_info:tcltk_get_parameter_free_guards_for_ops
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7591: bmachine:tcltk_get_specialized_invariant_for_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7600: tcltk_cbc_symbolic_invariant_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7610: before_after_predicates:tcltk_before_after_predicate_for_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7619: value_persistance:tcltk_load_constants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7629: runtime_profiler:tcltk_get_profile_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7648: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7653: model_checking_is_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7677: statistics
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7707: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7731: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7732: tcltk_get_constants_predicate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7740: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7742: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7743: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7749: "specfile:animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7753: bmachine:b_write_eventb_machine_to_classicalb_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7946: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7977: tcltk_machine_has_assertions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7986: bmachine:b_get_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8041: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8042: tcltk_get_constants_predicate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8117: tcltk_dbf_modes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8126: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8138: bmachine:b_get_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8146: tcltk_machine_has_assertions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8154: operation_name_not_yet_covered
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8160: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8197: tcltk_state_space_only_has_root_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8205: tcltk_search_among_existing_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8230: tcltk_set_dbf_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8247: "prolog_flag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8249: "nl
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8250: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8274: "statistics
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8276: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8281: tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8282: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8283: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8288: state_space:operation_name_not_yet_covered
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8291: model_checker:proof_info_model_checking_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8294: time_out_for_invariant
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8298: tcltk_hash_model_checking_imprecise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8302: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8305: state_error_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8311: state_error_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8362: tcltk_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8462: tcltk_run_ltsmin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8480: cbc_get_uncovered_events
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8484: sap:tcl_get_stored_test_cases
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8514: tcl_execute_stored_test_case
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8534: sap:tcl_generate_testcases
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8655: sap:tcl_create_local_testsuite
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8738: set_unicode_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8742: set_force_eventb_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8744: specfile:get_internal_representation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8752: unset_unicode_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8756: unset_force_eventb_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8761: predicate_debugger:tcltk_get_unsat_core_with_types
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8768: bmachine:b_show_eventb_as_classicalb
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8781: b_set_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8791: tk_get_error_span_linecol_for_main_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8795: get_error_span_linecol
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8799: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8803: source_profiler:source_profiler_enabled
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8804: source_profiler:tcltk_get_source_hit_location
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8820: "tools_commands:show_errors_with_bb_results
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8827: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8835: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8840: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8841: backup_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8848: tcltk_get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8861: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8871: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8896: tcltk_goto_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8904: tcltk_goto_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8913: tcltk_goto_a_non_resetable_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8922: tcltk_goto_a_non_deterministic_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8929: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8932: tcltk_goto_node_with_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8941: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8950: tcltk_goto_a_branching_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8965: tcltk_search_among_existing_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8969: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9017: tcltk_goto_event_list_property_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9021: sap:get_selected_events
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9022: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9037: tcltk_goto_state_enabling_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9040: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9065: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9067: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9094: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9134: ctl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9140: state_space:max_nr_of_new_nodes_limit_not_reached
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9146: state_space:max_nr_of_new_nodes_limit_not_reached
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9176: b_top_level_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9192: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9193: tcltk_cbc_find_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9206: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9211: tcltk_constraint_find_valid_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9215: tcltk_constraint_find_maximal_valid_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9219: tcltk_constraint_find_dynamic_assertion_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9227: b_get_machine_operation_parameter_names
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9229: current_state_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9243: "tcltk_constraint_find_valid_state_with_pred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9245: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9258: tcltk_perform_cbc_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9274: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9282: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9287: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9292: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9306: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9307: tcltk_constraint_based_check_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9321: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9339: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9340: tcltk_constraint_find_deadlock_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9348: error_or_warning_occured
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9357: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9362: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9363: tcltk_constraint_find_deadlock_state_with_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9376: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9381: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9382: tcltk_constraint_find_static_assertion_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9402: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9406: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9406: unfixed_deferred_set
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9502: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9536: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9543: and insert them to the listbox
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9582: tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9591: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9618: bmachine:bmachine_is_precompiled
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9618: tcltk_no_constants_or_no_inititalisation_found
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9619: current_state_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9620: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9649: tcltk_current_node_has_no_real_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9651: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9651: bmachine:bmachine_is_precompiled
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9651: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9651: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9653: tcltk_current_node_has_partial_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9654: preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9676: b_interpreter:tcltk_unsatisfiable_components_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9693: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9693: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9698: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9704: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9716: b_interpreter:tcltk_quick_describe_unsat_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9734: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9739: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9741: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9742: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9743: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9754: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9766: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9803: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9827: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9843: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9844: tcltk_state_exists_with_invariant_violated
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9851: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9883: tcltk_can_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9890: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9905: and insert them to the listbox
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9918: tcltk_get_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9934: and insert them
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9940: tcltk_get_state_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9954: and insert them to the listbox
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9961: tcltk_get_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9999: csp_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10011: tcltk_get_line_col
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10022: tcltk_is_sync_event
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10047: tcltk_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10061: tcltk_no_constants_or_no_inititalisation_found
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10066: tcltk_perform_nr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10078: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10088: tcltk_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10093: tcltk_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10119: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10274: get_cbc_data_base_id_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10274: get_cbc_data_base_text_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10482: tcltk_constraint_based_check_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10486: tcltk_cbc_find_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10490: tcltk_constraint_find_deadlock_state_with_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10493: assert_real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10499: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10501: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10517: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10523: tcltk_perform_cbc_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10571: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10593: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10631: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10672: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10724: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10786: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10965: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11038: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11049: "get_csp_assertions_as_string
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11159: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11175: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11177: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11208: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11440: "get_ltl_formulas_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11457: parse_and_load_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11498: "get_writable_compiled_filename
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11500: "parse_and_load_cspm_file_into_specific_pl_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11527: "generate_temporary_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11557: "eval_elapsed_time
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11574: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11574: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11577: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11580: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11871: "user: get_user_signal_ref
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11873: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11937: "tcltk_check_csp_assertion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12336: side
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12338: "tcltk_check_csp_assertion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12351: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12387: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12442: "get_csp_assertions_as_string
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12674: call and the implementation for reading the result from prolog
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12789: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12791: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12901: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12905: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12909: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12949: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12952: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12976: "tcltk_play_ltl_ctl_counterexample_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12992: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12995: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13007: haskell_csp:get_formulas_from_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13008: b_get_definition_string_list_from_spec
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13009: "
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13010: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13018: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13089: "ltl: parse_and_pp_ltl_formula
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13098: "ctl: parse_and_pp_ctl_formula
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13120: ctl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13121: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13173: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13210: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13236: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13238: haskell_csp:get_formulas_from_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13241: b_get_definition_string_list_from_spec
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13244: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13280: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13286: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13289: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13309: [subst 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13345: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13436: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13453: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13460: b_get_definition_string_from_spec
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13462: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13462: haskell_csp:get_formulas_from_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13516: b_get_definition_string_from_spec
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13565: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13570: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13663: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13679: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13687: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13705: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13709: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13773: "parsercall:get_java_fullversion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13778: compile_time_flags
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13799: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13918: "tcltk_save_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13931: "tcltk_load_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13951: "tcltk_save_specification_state_for_refinement
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13953: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13955: "tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13964: bmachine:b_get_refined_machine_name
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13986: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13988: "tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14062: b_get_refined_ancestors_names
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14145: tcltk_load_refine_spec_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14146: tcltk_refinement_search
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14153: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14180: "b_show_history:write_full_history_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14196: "state_viewer_images:html_print_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14218: "tcltk_save_history_as_trace_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14222: "tcltk_save_history_as_trace_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14276: "tcltk_check_state_sequence_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14279: "tcltk_check_sequence_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14283: test_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14316: "b_machine_hierarchy:write_dot_hierarchy_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14330: "meta_interface:command_preferences_category
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14340: "meta_interface:call_dot_command
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14353: "meta_interface:call_dot_command_for_expr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14376: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14379: "tcltk_print_states_for_dot_sfdp
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14381: "tcltk_print_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14391: "tcltk_print_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14395: "tcltk_print_states_for_dot_sfdp
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14411: "tcltk_print_neighbourhood_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14417: b_reset_machine_goal_from_DEFINITIONS
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14462: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14479: generate_dot_from_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14500: preferences:get_preference_with_warnings
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14515: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14516: preferences:get_preference_with_warnings
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14564: process_latex_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14567: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14581: preferences:get_preference_with_warnings
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14589: preferences:get_preference_with_warnings
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14602: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14607: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14612: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14632: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14664: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14673: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14673: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14691: current_state_corresponds_to_setup_constants_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14701: initialised_b_state_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14715: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14726: "compute_covered_values_for_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14733: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14740: "tcltk_compute_nr_covered_values_for_all_variables
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14756: "tcltk_evaluate_expression_over_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14772: current_state_corresponds_to_setup_constants_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14781: "tcltk_print_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14785: "state_custom_dot_graph:tcltk_generate_state_custom_dot_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14803: "tcltk_print_history_to_current_state_with_neighbors_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14819: "tcltk_print_shortest_trace_to_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14821: "tcltk_print_history_to_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14855: "state_space_reduction:tcltk_write_signature_merge_to_dotfile
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14872: "reduce_graph_state_space:print_subgraph_of_goal_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14874: "reduce_graph_state_space:print_subgraph_associated_with_invariant_violations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14888: "debug_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14889: "run_time_type_check_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14890: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14925: "tcltk_print_states_for_fdr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14926: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14934: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14941: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14947: "tcltk_print_states_for_fdr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14972: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14974: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15041: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15045: b_write_machine_representation_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15061: "tcltk_print_states_for_spin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15070: "promela_save_as_neverclaim
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15079: "well_def_analyser:analyse_wd_for_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15080: error_or_warning_occured
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15089: "bmachine_static_checks:extended_static_check_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15090: error_or_warning_occured
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15100: "well_def_analyser:tcltk_get_machine_wd_pos
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15156: "state_space:current_state_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15160: tcltk_get_image_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15175: get_animation_image_source_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15215: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15219: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15221: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15369: "tcltk_can_react_to_item_drag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15397: "tcltk_can_react_to_item_right_click
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15402: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15420: state_custom_dot_graph:state_custom_dot_graph_available
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15430: "tcltk_react_to_item_right_click
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15441: "tcltk_react_to_item_drag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15529: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15531: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15538: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15546: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15550: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15555: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15558: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15561: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15563: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15568: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15571: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15573: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15575: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15578: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15581: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15583: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15614: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15636: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15658: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15659: "ic3_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15664: ic3:counter_example_can_be_replayed
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15683: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15704: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15705: "tcltk_unsat_core_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15707: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15710: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15720: query e
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15722: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15739: reduce_graph_state_space:get_alphabet_signatures
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15747: "reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15769: reduce_graph_state_space:assert_all_transition_arg_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15770: reduce_graph_state_space:get_transition_arguments_from_source
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15774: "reduce_graph_state_space:transition_arg_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15792: which arguments we dont care about
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15798: "reduce_graph_state_space:get_transition_arguments_from_source
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15823: "reduce_graph_state_space:assert_transition_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15834: "reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15842: reduce_graph_state_space:use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15847: "reduce_graph_state_space:use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15875: "reduce_graph_state_space:use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15881: "reduce_graph_state_space:use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15954: "(reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15961: "retractall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15973: reduce_graph_state_space:user_has_made_op_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16070: pathes:runtime_application_path
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16072: absolute_file_name
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16074: absolute_file_name
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16076: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16080: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16085: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16090: tcltk_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16105: tcltk_cbc_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16118: "tcltk_cbc_enabling_relations_after_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16121: "tcltk_cbc_enabling_relations_for_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16132: tcltk_cbc_simultaneous_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16139: tcltk_cbc_dependence_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16144: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16145: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16152: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16153: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16165: tcltk_operations_covered_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16177: "tcltk_check_if_feasible_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16188: tcltk_compute_mcdc_operation_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16196: tcltk_compute_mcdc_invariant_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16204: tcltk_get_invariant_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16212: tcltk_cbc_cfg_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16218: b_read_write_info:tcltk_read_write_matrix
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16224: b_read_write_info:tcltk_variable_read_write_matrix
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16231: b_state_model_check:tcltk_cbc_constants_det_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16239: tcltk_create_dependence_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16244: tcltk_create_dependence_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16249: tcltk_create_enable_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16254: tcltk_create_enable_graph_por
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16259: tcltk_create_disable_graph_por
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16264: tcltk_dot_cfg_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16270: tcltk_disabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16290: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16533: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16536: prologTaskStart
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16556: "tools:walltime
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16563: prologTaskStep
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16572: prologTaskAbort
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16578: prologTaskFinish
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16579: "tools:walltime
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16590: Task 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16689: bvisual2:set_bvisual2_translation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16713: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:12: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:23: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:31: tcltk_tree_inspector:reset_tcltk_tree_inspector
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:49: tcltk_tree_inspector:tti_number_of_columns
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:64: tcltk_tree_inspector:tti_column_info
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:83: tcltk_tree_inspector:tti_column_info
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:132: tcltk_tree_inspector:tti_get_node_info
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:59: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:72: proz:startzconversiontests
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:104: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:107: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:122: preferences:backup_preferences
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:123: preferences:reset_for_benchmarking
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:124: preferences:deactivate_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:183: preferences:revert_preferences
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:184: preferences:activate_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:621: b_trace_checking:print_trace_as_fdr_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:952: analyze_hash_collisions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1019: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1021: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1106: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1113: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1115: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1120: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1122: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1125: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1127: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1129: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1131: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1664: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1666: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1745: get_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1760: preferences:clear_recent_documents 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2134: "preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2136: "eclipse_interface:ops_with_virtual_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2137: "eclipse_interface:ops_with_real_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2166: tcltk_mark_current_node_to_be_recomputed_wo_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2174: tcltk_mark_current_node_to_be_recomputed_with_random_enum
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2178: tcltk_finish_current_node_to_be_recomputed_with_random_enum
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2595: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2861: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3884: tcltk_clear_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3976: get_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4408: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4468: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4499: tcltk_clear_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4564: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5434: tcltk_reset
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5439: tcltk_fast_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5634: tcltk_execute_trace_to_current_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5670: tcltk_find_shortest_trace_to_current_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5728: preferences:backup_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5767: get_preferences_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5784: preferences:revert_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5792: reset_to_defaults
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5806: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5807: get_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5832: get_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5864: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5868: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5870: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6286: tcltk_top_level_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6466: {Query
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6567: tcltk_analyse
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6621: tcltk_analyse_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6632: tcltk_show_typing_of_variables_and_constants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7911: tcltk_reset
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8239: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8426: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8520: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8881: count_errors_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8884: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9011: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9276: tcltk_cbc_refinement_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9288: tcltk_constraint_based_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9601: tcltk_get_options_dest_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9641: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10312: findall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10416: findall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13647: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13649: host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13654: get_preferences_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13770: prob_licence
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13797: prob_licence
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13836: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13876: mc_summary
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13892: symmetry_summary
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14338: "command_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14350: "command_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14831: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14893: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14901: "tcltk_turn_debugging_on
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14903: "tcltk_turn_debugging_off
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14906: "turn_on_run_time_type_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14908: "turn_off_run_time_type_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14911: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14912: "debug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14915: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14916: "nodebug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14948: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14982: preferences:get_preference_with_warnings
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15009: preferences:get_preference_with_warnings
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15615: "bmc_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15637: "kinduction_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15684: "ctigar_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15856: "reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15862: "reduce_graph_state_space:set_use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15944: reduce_graph_state_space:user_made_op_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15963: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15974: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15975: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15996: reduce_graph_state_space:user_made_arg_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16009: "reduce_graph_state_space:set_use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16662: tcltk_set_initial_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16673: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6194: tcltk_compute_coverage_and_enabling
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6197: tcltk_compute_coverage_and_degree
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6200: tcltk_compute_min_max
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6203: tcltk_get_vacuous_invariants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6208: tcltk_get_vacuous_guards
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6213: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6454: {Query
