/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl:12: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl:90: ast_inspector:tcltk_get_node_info
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:20: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:43: tcltk_model_check
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:51: tcltk_goto_an_invariant_violation
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:152: system:environ
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:199: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:22: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:86: tcltk_bv_get_tops
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:125: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:133: "tcltk_bv_show_formula_as_dot_graph
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:142: "tcltk_bv_show_formula_as_dot_tree
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:152: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:160: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:162: tcltk_bv_get_unlimited_value
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:173: bv_show_formula_origin
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:234: "tcltk_bv_get_values
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:253: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:491: "current_expression
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:494: "bvisual2:bv_print_to_file
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:503: "current_expression
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:505: "bvisual2:bv_write_all_variables_and_constants
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:540: bv_formula_description
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:549: bv_is_typed_formula
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:550: bv_is_typed_predicate
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:559: bv_is_typed_identifier
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:658: "bvisual2:tcltk_register_new_user_formula
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:49: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:51: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:62: version:version
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:65: prolog_flag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:68: version:revision
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:70: version:lastchangeddate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:239: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:255: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:279: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:281: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:295: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:295: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:310: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:349: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:350: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:557: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:853: self_checks_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:859: self_checks_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:882: debug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:883: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:885: compile_time_flags:compile_time_flag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:908: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:914: (nl
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:919: state_space_initialise_with_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:998: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1010: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1014: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1040: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1043: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1046: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1049: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1079: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1084: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1156: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1165: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1178: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1182: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1193: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1197: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1208: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1210: error_or_warning_occured
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1237: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1284: "tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1286: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1323: "tcltk_show_expression_as_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1355: "tcltk_eval_as_table
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1356: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1414: "tcltk_explore_csp_process
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1417: get_csp_process_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1421: "tcltk_visualize_csp_process
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1430: "tcltk_visualize_csp_process
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1449: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1456: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1505: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1507: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1528: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1546: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1760: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1802: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1803: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1810: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1986: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1994: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1997: b_top_level_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1997: animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2003: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2037: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2054: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2076: tcltk_has_eventtrace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2090: tcltk_show_eventtrace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2102: tcltk_get_detailed_state_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2108: can_generate_dot_from_last_state_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2135: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2141: "eclipse_interface:ops_user_interrupt_occured
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2154: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2163: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2168: plugins:plugin_has_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2169: plugins:plugins_with_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2187: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2190: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2193: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2210: plugins:plugin_is_available_for_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2211: plugins:available_plugins_for_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2229: plugins:start_plugin_for_current_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2242: plugins:plugin_has_output
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2245: plugins:plugin_get_output
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2257: plugins:plugin_get_output
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2274: plugins:stop_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2285: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2288: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2297: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2299: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2307: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2363: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2374: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2386: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2389: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2583: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2599: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2619: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2621: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2623: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2624: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2805: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2808: "animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2946: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3269: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3271: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3702: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3710: parsercall:check_java_version
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3712: parsercall:get_version_from_parser
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3730: perform_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3743: perform_verbose_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3756: get_module_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3759: perform_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3820: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3823: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3877: plugins:plugin_file_extensions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3904: plugins:active_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3910: preferences:add_recent_document
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3924: "unset_tcltk_cspm_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3941: plugins:is_plugin_file_extension
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3949: plugins:available_plugins_for_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3978: tcltk_load_packaged_eventb_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3983: bmachine:b_show_machine_representation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4039: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4045: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4048: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4052: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4056: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4059: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4062: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4065: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4073: tcltk_get_command_line_file_to_open
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4080: tcltk_get_command_line_tcltk_commands
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4099: tcltk_open_xtl_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4122: tcltk_open_alloy_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4264: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4284: tcltk_open_z_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4307: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4335: eclipse_interface:load_prob_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4336: tcltk_open_b_file_for_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4339: set_animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4399: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4400: "tools:platform_is_64_bit
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4445: plugins:load_plugin_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4467: tcltk_open_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4483: "set_tcltk_cspm_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4494: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4573: tcltk_add_csp_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4626: tcltk_open_b_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4778: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4780: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4814: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4840: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4860: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4861: plugins:tcl_plugin_syntax_colouring
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4882: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4910: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4914: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4919: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4922: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4928: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4933: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4937: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4945: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4958: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4962: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4968: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4974: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4982: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4986: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4996: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5002: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5010: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5024: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5041: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5044: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5048: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5053: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5058: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5062: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5066: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5070: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5080: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5083: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5087: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5091: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5095: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5106: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5109: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5113: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5117: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5128: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5131: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5136: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5140: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5145: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5149: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5153: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5162: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5165: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5170: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5176: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5182: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5187: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5198: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5220: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5257: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5258: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5261: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5264: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5267: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5271: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5274: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5277: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5280: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5316: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5351: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5353: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5365: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5375: "b_show_history:write_values_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5403: preferences:add_recent_document
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5501: plugins:active_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5512: tcltk_prepare_for_reload
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5527: plugins:is_registered_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5575: tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5586: tcltk_random_perform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5591: tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5667: tcltk_random_perform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5670: tcltk_current_state_invariant_violated
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5679: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5707: tcltk_execute_until
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5727: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5728: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5741: "tcltk_execute_model
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5769: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5824: cli_prefs_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5825: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5827: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5830: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5836: tcltk_load_commandline_prefs_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5839: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5840: file_systems:file_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5841: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5843: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5963: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5976: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5978: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6000: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6003: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6085: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6091: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6106: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6107: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6113: preference_default_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6115: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6120: preference_default_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6122: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6133: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6133: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6134: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6141: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6150: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6158: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6260: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6264: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6268: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6305: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6306: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6310: model_checking_is_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6372: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6373: tcltk_unique_top_level_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6378: current_state_corresponds_to_setup_constants_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6451: "
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6477: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6477: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6483: b_get_machine_operation_parameter_names
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6486: b_get_operation_non_det_modifies
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6494: "tcltk_add_user_executed_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6581: query does not fail 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6582: interruptable_call(
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6593: query does not fail 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6594: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6595: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6597: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6651: interruptable_call(tcltk_debug_properties_or_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6689: tcltk_analyse_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6691: "register_conjunct_register_error_span
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6708: tcltk_state_exists_with_invariant_violated
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6727: "reset_conjunct_error_hook
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6740: b_reset_machine_goal_from_DEFINITIONS
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6765: tcltk_show_current_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6779: tcltk_clear_state_space_and_refocus_to_current_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6786: preferences:get_non_default_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6946: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6950: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6959: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6967: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6968: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6976: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7019: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7021: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7026: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7042: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7047: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7075: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7078: parsercall:ensure_console_parser_launched
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7221: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7293: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7300: last_expression_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7308: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7330: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7339: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7348: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7368: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7454: tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7460: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7463: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7482: "interruptable_tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7488: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7497: "b_simplifier: tcltk_simplify_b_predicate_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7500: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7518: get_error_positions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7525: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7551: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7687: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7688: popup
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7696: bmachine:tcltk_get_specialized_invariants_for_ops
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7702: b_read_write_info:tcltk_get_guards_for_ops
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7708: b_read_write_info:tcltk_get_parameter_free_guards_for_ops
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7717: bmachine:tcltk_get_specialized_invariant_for_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7725: tcltk_cbc_symbolic_invariant_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7735: before_after_predicates:tcltk_before_after_predicate_for_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7744: value_persistance:tcltk_load_constants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7754: runtime_profiler:tcltk_get_profile_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7773: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7778: model_checking_is_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7809: statistics
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7839: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7862: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7863: tcltk_get_constants_predicate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7871: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7873: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7874: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7880: "specfile:animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7884: bmachine:b_write_eventb_machine_to_classicalb_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8077: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8108: tcltk_machine_has_assertions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8117: bmachine:b_get_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8172: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8173: tcltk_get_constants_predicate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8248: tcltk_dbf_modes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8257: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8269: bmachine:b_get_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8277: tcltk_machine_has_assertions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8284: operation_name_not_yet_covered
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8290: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8327: tcltk_state_space_only_has_root_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8335: tcltk_search_among_existing_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8360: tcltk_set_dbf_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8377: "prolog_flag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8379: "nl
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8380: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8404: "statistics
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8406: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8411: tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8412: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8413: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8418: state_space:operation_name_not_yet_covered
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8421: model_checker:proof_info_model_checking_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8424: time_out_for_invariant
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8428: tcltk_hash_model_checking_imprecise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8432: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8437: state_error_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8487: tcltk_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8583: tcltk_run_ltsmin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8598: cbc_get_uncovered_events
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8602: sap:tcl_get_stored_test_cases
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8631: tcl_execute_stored_test_case
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8651: sap:tcl_generate_testcases
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8772: sap:tcl_create_local_testsuite
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8855: set_unicode_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8858: specfile:get_internal_representation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8866: unset_unicode_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8872: predicate_debugger:tcltk_get_unsat_core_with_types
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8879: bmachine:b_show_eventb_as_classicalb
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8892: b_set_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8902: get_error_span_linecol_for_main_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8906: get_error_span_linecol
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8910: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8914: source_profiler:source_profiler_enabled
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8915: source_profiler:tcltk_get_source_hit_location
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8931: "tools_commands:show_errors_with_bb_results
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8938: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8946: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8951: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8952: backup_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8959: tcltk_get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8975: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8985: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9010: tcltk_goto_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9018: tcltk_goto_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9027: tcltk_goto_a_non_resetable_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9036: tcltk_goto_a_non_deterministic_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9043: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9046: tcltk_goto_node_with_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9055: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9064: tcltk_goto_a_branching_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9079: tcltk_search_among_existing_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9083: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9131: tcltk_goto_event_list_property_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9135: sap:get_selected_events
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9136: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9151: tcltk_goto_state_enabling_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9154: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9179: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9181: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9208: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9248: ctl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9254: state_space:max_nr_of_new_nodes_limit_not_reached
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9260: state_space:max_nr_of_new_nodes_limit_not_reached
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9290: b_top_level_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9306: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9307: tcltk_cbc_find_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9320: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9325: tcltk_constraint_find_valid_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9331: b_get_machine_operation_parameter_names
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9333: current_state_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9347: "tcltk_constraint_find_valid_state_with_pred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9349: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9362: tcltk_perform_cbc_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9378: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9386: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9391: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9396: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9403: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9404: tcltk_constraint_based_check_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9418: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9436: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9437: tcltk_constraint_find_deadlock_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9445: error_or_warning_occured
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9454: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9459: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9460: tcltk_constraint_find_deadlock_state_with_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9473: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9478: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9479: tcltk_constraint_find_static_assertion_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9499: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9503: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9503: unfixed_deferred_set
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9599: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9633: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9640: and insert them to the listbox
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9679: tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9688: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9715: bmachine:bmachine_is_precompiled
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9715: tcltk_no_constants_or_no_inititalisation_found
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9716: current_state_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9717: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9746: tcltk_current_node_has_no_real_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9748: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9748: bmachine:bmachine_is_precompiled
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9748: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9748: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9750: tcltk_current_node_has_partial_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9751: preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9772: b_interpreter:tcltk_unsatisfiable_components_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9788: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9788: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9793: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9799: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9810: b_interpreter:tcltk_quick_describe_unsat_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9821: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9826: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9828: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9829: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9830: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9841: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9853: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9890: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9914: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9930: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9931: tcltk_state_exists_with_invariant_violated
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9938: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9970: tcltk_can_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9977: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9992: and insert them to the listbox
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10005: tcltk_get_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10021: and insert them
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10027: tcltk_get_state_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10041: and insert them to the listbox
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10048: tcltk_get_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10086: csp_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10098: tcltk_get_line_col
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10109: tcltk_is_sync_event
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10134: tcltk_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10148: tcltk_no_constants_or_no_inititalisation_found
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10153: tcltk_perform_nr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10165: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10175: tcltk_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10180: tcltk_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10206: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10361: get_cbc_data_base_id_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10361: get_cbc_data_base_text_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10569: tcltk_constraint_based_check_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10573: tcltk_cbc_find_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10577: tcltk_constraint_find_deadlock_state_with_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10580: assert_real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10586: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10588: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10604: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10610: tcltk_perform_cbc_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10658: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10680: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10718: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10759: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10811: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10873: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11052: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11125: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11136: "get_csp_assertions_as_string
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11246: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11262: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11264: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11295: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11527: "get_ltl_formulas_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11544: parse_and_load_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11585: "get_writable_compiled_filename
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11587: "parse_and_load_cspm_file_into_specific_pl_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11614: "generate_temporary_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11644: "eval_elapsed_time
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11661: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11661: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11664: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11667: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11958: "user: get_user_signal_ref
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11960: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12024: "tcltk_check_csp_assertion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12423: side
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12425: "tcltk_check_csp_assertion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12438: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12474: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12529: "get_csp_assertions_as_string
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12761: call and the implementation for reading the result from prolog
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12876: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12878: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12988: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12992: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12996: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13036: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13039: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13063: "tcltk_play_ltl_ctl_counterexample_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13079: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13082: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13094: haskell_csp:get_formulas_from_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13095: b_get_definition_string_list_from_spec
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13096: "
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13097: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13105: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13176: "ltl: parse_and_pp_ltl_formula
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13185: "ctl: parse_and_pp_ctl_formula
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13207: ctl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13208: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13260: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13297: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13323: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13325: haskell_csp:get_formulas_from_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13328: b_get_definition_string_list_from_spec
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13331: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13367: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13373: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13376: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13396: [subst 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13432: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13523: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13540: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13547: b_get_definition_string_from_spec
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13549: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13549: haskell_csp:get_formulas_from_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13603: b_get_definition_string_from_spec
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13652: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13657: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13750: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13766: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13774: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13792: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13796: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13860: "parsercall:get_java_fullversion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13865: compile_time_flags
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13997: "tcltk_save_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14010: "tcltk_load_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14030: "tcltk_save_specification_state_for_refinement
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14032: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14034: "tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14043: bmachine:b_get_machine_refinement_hierarchy
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14065: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14067: "tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14141: b_get_machine_refinement_hierarchy
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14224: tcltk_load_refine_spec_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14225: tcltk_refinement_search
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14232: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14259: "b_show_history:write_full_history_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14275: "state_viewer_images:html_print_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14297: "tcltk_save_history_as_trace_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14301: "tcltk_save_history_as_trace_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14355: "tcltk_check_state_sequence_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14358: "tcltk_check_sequence_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14362: test_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14395: "b_machine_hierarchy:write_dot_hierarchy_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14407: "meta_interface:command_preferences_category
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14414: "meta_interface:call_dot_command
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14424: "meta_interface:command_preferences_category
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14432: "meta_interface:call_dot_command_for_expr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14455: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14458: "tcltk_print_states_for_dot_sfdp
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14460: "tcltk_print_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14470: "tcltk_print_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14474: "tcltk_print_states_for_dot_sfdp
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14490: "tcltk_print_neighbourhood_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14496: b_reset_machine_goal_from_DEFINITIONS
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14541: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14558: generate_dot_from_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14579: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14594: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14595: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14615: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14622: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14634: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14639: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14644: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14664: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14696: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14705: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14705: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14723: current_state_corresponds_to_fully_setup_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14733: initialised_b_state_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14747: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14758: "compute_covered_values_for_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14765: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14772: "tcltk_compute_nr_covered_values_for_all_variables
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14788: "tcltk_evaluate_expression_over_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14804: current_state_corresponds_to_setup_constants_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14813: "tcltk_print_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14817: "state_custom_dot_graph:tcltk_generate_state_custom_dot_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14835: "tcltk_print_history_to_current_state_with_neighbors_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14851: "tcltk_print_shortest_trace_to_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14853: "tcltk_print_history_to_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14887: "state_space_reduction:tcltk_write_signature_merge_to_dotfile
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14904: "reduce_graph_state_space:print_subgraph_of_goal_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14906: "reduce_graph_state_space:print_subgraph_associated_with_invariant_violations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14920: "debug_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14921: "run_time_type_check_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14922: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14957: "tcltk_print_states_for_fdr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14958: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14966: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14973: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14979: "tcltk_print_states_for_fdr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15004: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15006: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15073: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15077: b_write_machine_representation_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15093: "tcltk_print_states_for_spin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15102: "promela_save_as_neverclaim
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15161: "state_space:current_state_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15165: tcltk_get_image_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15180: get_animation_image_source_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15220: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15224: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15226: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15374: "tcltk_can_react_to_item_drag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15402: "tcltk_can_react_to_item_right_click
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15407: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15425: state_custom_dot_graph:state_custom_dot_graph_available
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15435: "tcltk_react_to_item_right_click
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15446: "tcltk_react_to_item_drag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15534: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15536: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15543: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15551: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15555: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15560: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15563: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15566: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15568: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15573: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15576: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15578: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15580: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15583: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15586: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15588: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15619: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15641: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15663: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15664: "ic3_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15669: ic3:counter_example_can_be_replayed
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15688: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15706: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15707: "tcltk_unsat_core_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15717: query e
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15719: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15736: reduce_graph_state_space:get_alphabet_signatures
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15744: "reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15766: reduce_graph_state_space:assert_all_transition_arg_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15767: reduce_graph_state_space:get_transition_arguments_from_source
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15771: "reduce_graph_state_space:transition_arg_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15789: which arguments we dont care about
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15795: "reduce_graph_state_space:get_transition_arguments_from_source
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15820: "reduce_graph_state_space:assert_transition_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15831: "reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15839: reduce_graph_state_space:use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15844: "reduce_graph_state_space:use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15872: "reduce_graph_state_space:use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15878: "reduce_graph_state_space:use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15951: "(reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15958: "retractall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15970: reduce_graph_state_space:user_has_made_op_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16067: pathes:runtime_application_path
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16069: absolute_file_name
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16071: absolute_file_name
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16073: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16077: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16082: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16087: tcltk_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16102: tcltk_cbc_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16115: "tcltk_cbc_enabling_relations_after_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16118: "tcltk_cbc_enabling_relations_for_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16129: tcltk_cbc_simultaneous_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16136: tcltk_cbc_dependence_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16141: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16142: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16154: tcltk_operations_covered_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16166: "tcltk_check_if_feasible_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16177: tcltk_compute_mcdc_operation_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16185: tcltk_compute_mcdc_invariant_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16193: tcltk_cbc_cfg_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16199: b_read_write_info:tcltk_read_write_matrix
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16205: b_read_write_info:tcltk_variable_read_write_matrix
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16213: tcltk_create_dependence_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16218: tcltk_create_dependence_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16223: tcltk_create_enable_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16228: tcltk_create_enable_graph_por
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16233: tcltk_create_disable_graph_por
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16238: tcltk_dot_cfg_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16244: tcltk_disabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16264: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16507: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16510: prologTaskStart
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16530: "tools:walltime
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16537: prologTaskStep
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16546: prologTaskAbort
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16552: prologTaskFinish
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16553: "tools:walltime
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16564: Task 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16663: bvisual2:set_bvisual2_translation_mode
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:12: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:23: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:31: tcltk_tree_inspector:reset_tcltk_tree_inspector
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:49: tcltk_tree_inspector:tti_number_of_columns
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:64: tcltk_tree_inspector:tti_column_info
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:83: tcltk_tree_inspector:tti_column_info
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:132: tcltk_tree_inspector:tti_get_node_info
/Users/leuschel/git_root/prob_prolog/tcl/unused.tcl:10: "cspm_file_add_remove_unicode
/Users/leuschel/git_root/prob_prolog/tcl/unused.tcl:17: "cspm_file_add_remove_unicode
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:56: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:69: proz:startzconversiontests
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:101: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:104: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:119: preferences:backup_preferences
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:120: preferences:reset_for_benchmarking
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:121: preferences:deactivate_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:180: preferences:revert_preferences
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:181: preferences:activate_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:604: b_trace_checking:print_trace_as_fdr_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:927: analyze_hash_collisions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1004: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1006: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1092: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1099: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1101: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1106: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1108: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1111: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1113: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1115: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1117: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1644: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1646: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1725: get_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1740: preferences:clear_recent_documents 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2118: "preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2120: "eclipse_interface:ops_with_virtual_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2121: "eclipse_interface:ops_with_real_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2150: tcltk_mark_current_node_to_be_recomputed_wo_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2158: tcltk_mark_current_node_to_be_recomputed_with_random_enum
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2162: tcltk_finish_current_node_to_be_recomputed_with_random_enum
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2670: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2936: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3974: tcltk_clear_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4066: get_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4518: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4579: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4610: tcltk_clear_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4664: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5560: tcltk_reset
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5565: tcltk_fast_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5760: tcltk_execute_trace_to_current_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5796: tcltk_find_shortest_trace_to_current_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5854: preferences:backup_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5893: get_preferences_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5910: preferences:revert_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5918: reset_to_defaults
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5932: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5933: get_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5958: get_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5990: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5994: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5996: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6412: tcltk_top_level_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6592: {Query
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6693: tcltk_analyse
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6747: tcltk_analyse_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6758: tcltk_show_typing_of_variables_and_constants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8042: tcltk_reset
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8369: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8551: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8637: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8995: count_errors_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8998: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9125: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9380: tcltk_cbc_refinement_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9392: tcltk_constraint_based_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9698: tcltk_get_options_dest_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9738: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10399: findall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10503: findall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13734: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13736: host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13741: get_preferences_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13857: prob_licence
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13884: prob_licence
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13915: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13955: mc_summary
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13971: symmetry_summary
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14406: "command_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14423: "command_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14863: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14925: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14933: "tcltk_turn_debugging_on
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14935: "tcltk_turn_debugging_off
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14938: "turn_on_run_time_type_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14940: "turn_off_run_time_type_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14943: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14944: "debug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14947: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14948: "nodebug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14980: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15014: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15041: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15620: "bmc_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15642: "kinduction_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15689: "ctigar_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15853: "reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15859: "reduce_graph_state_space:set_use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15941: reduce_graph_state_space:user_made_op_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15960: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15971: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15972: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15993: reduce_graph_state_space:user_made_arg_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16006: "reduce_graph_state_space:set_use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16636: tcltk_set_initial_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16647: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6320: tcltk_compute_coverage_and_enabling
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6323: tcltk_compute_coverage_and_degree
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6326: tcltk_compute_min_max
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6329: tcltk_get_vacuous_invariants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6334: tcltk_get_vacuous_guards
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6339: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6580: {Query
