/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl:12: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl:90: ast_inspector:tcltk_get_node_info
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:20: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:43: tcltk_model_check
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:51: tcltk_goto_an_invariant_violation
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:152: system:environ
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:199: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:22: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:86: tcltk_bv_get_tops
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:125: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:132: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:139: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:147: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:149: tcltk_bv_get_unlimited_value
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:160: bv_show_formula_origin
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:221: "tcltk_bv_get_values
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:240: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:478: "current_expression
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:481: "bvisual2:bv_print_to_file
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:490: "current_expression
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:492: "bvisual2:bv_write_all_variables_and_constants
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:527: bv_formula_description
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:633: "bvisual2:tcltk_register_new_user_formula
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:49: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:51: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:62: version:version
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:65: prolog_flag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:68: version:revision
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:70: version:lastchangeddate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:239: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:255: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:279: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:281: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:295: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:295: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:310: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:349: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:350: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:557: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:853: self_checks_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:859: self_checks_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:882: debug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:883: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:885: compile_time_flags:compile_time_flag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:908: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:914: (nl
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:919: state_space_initialise_with_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:998: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1010: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1014: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1040: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1043: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1046: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1049: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1079: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1084: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1156: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1165: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1178: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1182: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1193: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1197: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1208: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1210: error_or_warning_occured
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1237: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1284: "tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1286: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1329: "tcltk_show_expression_as_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1347: "tcltk_eval_as_table
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1348: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1406: "tcltk_explore_csp_process
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1409: get_csp_process_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1413: "tcltk_visualize_csp_process
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1422: "tcltk_visualize_csp_process
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1441: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1448: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1497: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1499: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1520: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1538: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1752: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1794: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1795: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1802: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1978: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1986: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1990: {tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2024: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2041: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2063: tcltk_has_eventtrace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2077: tcltk_show_eventtrace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2089: tcltk_get_detailed_state_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2095: can_generate_dot_from_last_state_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2122: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2128: "eclipse_interface:ops_user_interrupt_occured
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2141: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2150: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2155: plugins:plugin_has_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2156: plugins:plugins_with_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2174: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2177: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2180: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2197: plugins:plugin_is_available_for_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2198: plugins:available_plugins_for_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2216: plugins:start_plugin_for_current_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2229: plugins:plugin_has_output
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2232: plugins:plugin_get_output
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2244: plugins:plugin_get_output
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2261: plugins:stop_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2272: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2275: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2284: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2286: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2294: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2350: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2361: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2373: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2376: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2570: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2586: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2606: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2608: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2610: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2611: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2792: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2795: "animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2933: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3254: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3256: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3687: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3695: parsercall:check_java_version
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3697: parsercall:get_version_from_parser
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3715: perform_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3728: perform_verbose_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3741: get_module_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3744: perform_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3805: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3808: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3862: plugins:plugin_file_extensions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3889: plugins:active_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3895: preferences:add_recent_document
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3909: "unset_tcltk_cspm_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3928: plugins:is_plugin_file_extension
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3936: plugins:available_plugins_for_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3965: tcltk_load_packaged_eventb_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3970: bmachine:b_show_machine_representation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4026: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4032: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4035: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4039: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4043: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4046: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4049: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4052: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4060: tcltk_get_command_line_file_to_open
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4067: tcltk_get_command_line_tcltk_commands
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4086: tcltk_open_xtl_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4109: tcltk_open_alloy_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4251: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4271: tcltk_open_z_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4294: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4322: eclipse_interface:load_prob_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4323: tcltk_open_b_file_for_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4326: set_animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4386: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4387: "tools:platform_is_64_bit
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4432: plugins:load_plugin_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4458: tcltk_open_promela_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4487: tcltk_open_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4503: "set_tcltk_cspm_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4514: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4593: tcltk_add_csp_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4652: tcltk_open_b_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4789: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4791: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4825: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4851: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4871: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4872: plugins:tcl_plugin_syntax_colouring
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4893: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4921: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4925: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4930: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4933: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4939: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4944: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4948: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4956: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4969: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4973: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4979: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4985: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4993: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4997: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5007: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5013: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5021: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5047: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5050: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5054: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5059: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5064: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5068: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5072: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5076: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5086: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5089: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5093: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5097: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5101: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5112: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5115: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5119: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5123: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5133: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5136: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5141: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5146: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5150: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5155: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5160: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5165: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5175: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5178: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5183: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5187: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5192: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5196: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5200: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5209: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5212: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5217: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5223: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5229: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5234: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5245: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5267: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5296: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5333: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5334: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5337: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5340: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5343: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5347: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5350: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5353: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5356: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5392: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5427: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5429: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5441: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5451: "b_show_history:write_values_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5479: preferences:add_recent_document
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5577: plugins:active_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5588: tcltk_prepare_for_reload
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5605: plugins:is_registered_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5653: tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5664: tcltk_random_perform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5669: tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5745: tcltk_random_perform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5748: tcltk_current_state_invariant_violated
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5757: {tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5785: tcltk_execute_until
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5805: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5806: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5819: "tcltk_execute_model
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5847: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5904: cli_prefs_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5905: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5907: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5910: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5916: tcltk_load_commandline_prefs_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5919: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5920: file_systems:file_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5921: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5923: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6045: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6058: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6060: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6082: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6085: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6167: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6173: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6188: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6189: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6195: preference_default_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6197: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6202: preference_default_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6204: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6215: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6215: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6216: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6223: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6232: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6240: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6342: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6346: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6350: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6387: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6388: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6392: model_checking_is_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6454: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6455: tcltk_unique_top_level_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6460: current_state_corresponds_to_setup_constants_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6533: "
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6560: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6560: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6566: b_get_machine_operation_parameter_names
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6569: b_get_operation_non_det_modifies
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6577: "tcltk_add_user_executed_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6662: query does not fail 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6663: interruptable_call(
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6674: query does not fail 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6675: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6676: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6678: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6732: interruptable_call(tcltk_debug_properties_or_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6770: tcltk_analyse_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6772: "register_conjunct_register_error_span
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6789: tcltk_state_exists_with_invariant_violated
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6808: "reset_conjunct_error_hook
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6821: b_reset_machine_goal_from_DEFINITIONS
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6846: tcltk_show_current_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6860: tcltk_clear_state_space_and_refocus_to_current_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6867: preferences:get_non_default_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7027: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7031: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7040: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7048: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7049: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7057: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7100: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7102: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7107: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7123: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7128: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7156: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7159: parsercall:ensure_console_parser_launched
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7302: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7374: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7381: last_expression_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7389: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7411: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7420: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7429: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7449: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7535: tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7541: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7544: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7563: "interruptable_tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7569: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7578: "b_simplifier: tcltk_simplify_b_predicate_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7581: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7599: get_error_positions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7606: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7632: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7768: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7769: popup
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7777: bmachine:tcltk_get_specialized_invariants_for_ops
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7783: b_read_write_info:tcltk_get_guards_for_ops
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7789: b_read_write_info:tcltk_get_parameter_free_guards_for_ops
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7798: bmachine:tcltk_get_specialized_invariant_for_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7806: tcltk_cbc_symbolic_invariant_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7816: before_after_predicates:tcltk_before_after_predicate_for_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7825: value_persistance:tcltk_load_constants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7835: runtime_profiler:tcltk_get_profile_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7854: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7859: model_checking_is_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7918: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7941: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7942: tcltk_get_constants_predicate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7950: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7952: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7953: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7959: "specfile:animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7963: bmachine:b_write_eventb_machine_to_classicalb_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8156: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8187: tcltk_machine_has_assertions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8196: bmachine:b_get_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8251: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8252: tcltk_get_constants_predicate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8327: tcltk_dbf_modes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8336: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8348: bmachine:b_get_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8356: tcltk_machine_has_assertions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8363: operation_name_not_yet_covered
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8369: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8406: tcltk_state_space_only_has_root_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8414: tcltk_search_among_existing_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8439: tcltk_set_dbf_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8456: "prolog_flag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8458: "nl
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8459: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8483: "statistics
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8485: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8490: tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8491: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8492: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8497: state_space:operation_name_not_yet_covered
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8500: model_checker:proof_info_model_checking_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8503: time_out_for_invariant
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8507: tcltk_hash_model_checking_imprecise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8511: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8516: state_error_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8566: tcltk_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8662: tcltk_run_ltsmin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8677: cbc_get_uncovered_events
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8681: sap:tcl_get_stored_test_cases
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8710: tcl_execute_stored_test_case
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8730: sap:tcl_generate_testcases
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8851: sap:tcl_create_local_testsuite
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8934: set_unicode_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8937: specfile:get_internal_representation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8945: unset_unicode_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8951: predicate_debugger:tcltk_get_unsat_core_with_types
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8958: bmachine:b_show_eventb_as_classicalb
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8971: b_set_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8981: get_error_span_linecol_for_main_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8985: get_error_span_linecol
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8989: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8993: source_profiler:source_profiler_enabled
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8994: source_profiler:tcltk_get_source_hit_location
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9010: "tools_commands:show_errors_with_bb_results
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9017: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9025: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9030: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9031: backup_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9038: tcltk_get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9054: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9064: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9089: tcltk_goto_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9097: tcltk_goto_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9106: tcltk_goto_a_non_resetable_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9115: tcltk_goto_a_non_deterministic_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9122: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9125: tcltk_goto_node_with_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9134: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9143: tcltk_goto_a_branching_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9158: tcltk_search_among_existing_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9162: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9210: tcltk_goto_event_list_property_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9214: sap:get_selected_events
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9215: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9230: tcltk_goto_state_enabling_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9233: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9258: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9260: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9287: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9327: ctl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9333: state_space:max_nr_of_new_nodes_limit_not_reached
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9339: state_space:max_nr_of_new_nodes_limit_not_reached
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9369: b_top_level_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9372: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9373: tcltk_cbc_find_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9386: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9394: tcltk_constraint_find_valid_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9400: b_get_machine_operation_parameter_names
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9402: current_state_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9416: "tcltk_constraint_find_valid_state_with_pred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9418: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9431: tcltk_perform_cbc_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9447: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9455: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9460: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9465: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9472: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9473: tcltk_constraint_based_check_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9487: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9505: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9506: tcltk_constraint_find_deadlock_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9514: error_or_warning_occured
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9523: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9528: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9529: tcltk_constraint_find_deadlock_state_with_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9542: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9547: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9548: tcltk_constraint_find_static_assertion_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9568: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9572: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9572: unfixed_deferred_set
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9668: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9702: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9709: and insert them to the listbox
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9748: {tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9757: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9784: bmachine:bmachine_is_precompiled
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9784: tcltk_no_constants_or_no_inititalisation_found
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9785: current_state_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9786: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9815: tcltk_current_node_has_no_real_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9817: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9817: bmachine:bmachine_is_precompiled
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9817: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9817: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9819: tcltk_current_node_has_partial_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9820: preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9841: b_interpreter:tcltk_unsatisfiable_components_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9857: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9857: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9862: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9868: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9879: b_interpreter:tcltk_quick_describe_unsat_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9890: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9895: {tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9897: {get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9898: {get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9899: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9910: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9922: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9959: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9983: {tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9999: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10000: tcltk_state_exists_with_invariant_violated
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10007: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10039: tcltk_can_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10046: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10061: and insert them to the listbox
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10073: {tcltk_get_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10090: and insert them
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10096: {tcltk_get_state_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10110: and insert them to the listbox
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10117: {tcltk_get_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10155: csp_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10167: tcltk_get_line_col
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10178: tcltk_is_sync_event
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10203: tcltk_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10217: tcltk_no_constants_or_no_inititalisation_found
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10222: tcltk_perform_nr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10234: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10244: tcltk_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10249: tcltk_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10275: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10430: get_cbc_data_base_id_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10430: get_cbc_data_base_text_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10638: tcltk_constraint_based_check_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10642: tcltk_cbc_find_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10646: tcltk_constraint_find_deadlock_state_with_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10649: assert_real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10655: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10657: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10673: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10679: tcltk_perform_cbc_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10727: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10749: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10787: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10828: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10880: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10942: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11121: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11194: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11205: "get_csp_assertions_as_string
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11315: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11331: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11333: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11364: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11596: "get_ltl_formulas_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11613: parse_and_load_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11654: "get_writable_compiled_filename
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11656: "parse_and_load_cspm_file_into_specific_pl_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11683: "generate_temporary_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11713: "eval_elapsed_time
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11730: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11730: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11733: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11736: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12027: "user: get_user_signal_ref
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12029: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12093: "tcltk_check_csp_assertion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12492: side
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12494: "tcltk_check_csp_assertion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12507: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12543: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12598: "get_csp_assertions_as_string
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12830: call and the implementation for reading the result from prolog
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12945: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12947: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13057: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13061: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13065: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13105: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13108: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13132: "tcltk_play_ltl_ctl_counterexample_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13148: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13151: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13163: haskell_csp:get_formulas_from_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13164: b_get_definition_string_list_from_spec
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13165: "
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13166: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13174: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13245: "ltl: parse_and_pp_ltl_formula
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13254: "ctl: parse_and_pp_ctl_formula
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13276: ctl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13277: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13329: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13366: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13392: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13394: haskell_csp:get_formulas_from_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13397: b_get_definition_string_list_from_spec
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13400: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13436: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13442: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13445: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13465: [subst 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13501: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13592: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13609: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13616: b_get_definition_string_from_spec
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13618: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13618: haskell_csp:get_formulas_from_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13672: b_get_definition_string_from_spec
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13721: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13726: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13819: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13835: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13843: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13861: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13865: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13929: "parsercall:get_java_fullversion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13934: compile_time_flags
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14066: "tcltk_save_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14079: "tcltk_load_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14099: "tcltk_save_specification_state_for_refinement
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14101: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14103: "tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14112: {bmachine:b_get_machine_refinement_hierarchy
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14134: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14136: "tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14210: {b_get_machine_refinement_hierarchy
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14293: tcltk_load_refine_spec_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14294: tcltk_refinement_search
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14301: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14328: "b_show_history:write_full_history_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14344: "state_viewer_images:html_print_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14366: "tcltk_save_history_as_trace_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14370: "tcltk_save_history_as_trace_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14424: "tcltk_check_state_sequence_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14427: "tcltk_check_sequence_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14431: test_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14464: "b_machine_hierarchy:write_dot_hierarchy_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14476: "meta_interface:command_preferences_category
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14483: "meta_interface:call_dot_command
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14493: "meta_interface:command_preferences_category
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14501: "meta_interface:call_dot_command_for_expr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14524: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14527: "tcltk_print_states_for_dot_sfdp
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14529: "tcltk_print_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14539: "tcltk_print_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14543: "tcltk_print_states_for_dot_sfdp
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14559: "tcltk_print_neighbourhood_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14565: b_reset_machine_goal_from_DEFINITIONS
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14610: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14627: generate_dot_from_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14648: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14663: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14664: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14684: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14691: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14703: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14708: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14713: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14733: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14765: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14774: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14774: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14792: current_state_corresponds_to_fully_setup_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14802: initialised_b_state_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14816: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14827: "compute_covered_values_for_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14834: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14841: "tcltk_compute_nr_covered_values_for_all_variables
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14857: "tcltk_evaluate_expression_over_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14873: current_state_corresponds_to_setup_constants_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14882: "tcltk_print_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14886: "state_custom_dot_graph:tcltk_generate_state_custom_dot_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14904: "tcltk_print_history_to_current_state_with_neighbors_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14920: "tcltk_print_shortest_trace_to_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14922: "tcltk_print_history_to_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14956: "state_space_reduction:tcltk_write_signature_merge_to_dotfile
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14973: "reduce_graph_state_space:print_subgraph_of_goal_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14975: "reduce_graph_state_space:print_subgraph_associated_with_invariant_violations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14989: "debug_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14990: "run_time_type_check_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14991: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15026: "tcltk_print_states_for_fdr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15027: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15035: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15042: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15048: "tcltk_print_states_for_fdr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15073: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15075: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15142: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15146: b_write_machine_representation_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15162: "tcltk_print_states_for_spin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15171: "promela_save_as_neverclaim
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15230: "state_space:current_state_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15234: tcltk_get_image_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15249: get_animation_image_source_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15289: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15293: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15295: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15443: "tcltk_can_react_to_item_drag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15471: "tcltk_can_react_to_item_right_click
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15476: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15494: state_custom_dot_graph:state_custom_dot_graph_available
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15504: "tcltk_react_to_item_right_click
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15515: "tcltk_react_to_item_drag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15603: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15605: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15612: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15620: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15624: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15629: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15632: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15635: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15637: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15642: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15645: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15647: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15649: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15652: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15655: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15657: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15688: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15710: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15732: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15733: "ic3_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15738: ic3:counter_example_can_be_replayed
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15757: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15775: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15776: "tcltk_unsat_core_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15786: query e
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15788: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15805: reduce_graph_state_space:get_alphabet_signatures
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15813: "reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15835: reduce_graph_state_space:assert_all_transition_arg_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15836: reduce_graph_state_space:get_transition_arguments_from_source
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15840: "reduce_graph_state_space:transition_arg_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15858: which arguments we dont care about
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15864: "reduce_graph_state_space:get_transition_arguments_from_source
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15889: "reduce_graph_state_space:assert_transition_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15900: "reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15908: reduce_graph_state_space:use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15913: "reduce_graph_state_space:use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15941: "reduce_graph_state_space:use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15947: "reduce_graph_state_space:use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16020: "(reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16027: "retractall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16039: reduce_graph_state_space:user_has_made_op_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16136: pathes:runtime_application_path
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16138: absolute_file_name
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16140: absolute_file_name
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16142: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16146: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16151: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16156: tcltk_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16171: tcltk_cbc_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16184: "tcltk_cbc_enabling_relations_after_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16187: "tcltk_cbc_enabling_relations_for_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16198: tcltk_cbc_simultaneous_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16205: tcltk_cbc_dependence_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16210: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16211: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16223: tcltk_operations_covered_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16235: "tcltk_check_if_feasible_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16246: tcltk_compute_mcdc_operation_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16254: tcltk_compute_mcdc_invariant_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16262: tcltk_cbc_cfg_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16268: b_read_write_info:tcltk_read_write_matrix
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16274: b_read_write_info:tcltk_variable_read_write_matrix
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16282: tcltk_create_dependence_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16287: tcltk_create_dependence_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16292: tcltk_create_enable_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16297: tcltk_create_enable_graph_por
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16302: tcltk_create_disable_graph_por
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16307: tcltk_dot_cfg_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16313: tcltk_disabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16333: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16576: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16579: prologTaskStart
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16599: "tools:walltime
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16606: prologTaskStep
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16615: prologTaskAbort
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16621: prologTaskFinish
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16622: "tools:walltime
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16633: Task 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16732: bvisual2:set_bvisual2_translation_mode
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:12: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:23: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:31: tcltk_tree_inspector:reset_tcltk_tree_inspector
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:49: tcltk_tree_inspector:tti_number_of_columns
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:64: tcltk_tree_inspector:tti_column_info
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:83: tcltk_tree_inspector:tti_column_info
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:132: tcltk_tree_inspector:tti_get_node_info
/Users/leuschel/git_root/prob_prolog/tcl/unused.tcl:10: "cspm_file_add_remove_unicode
/Users/leuschel/git_root/prob_prolog/tcl/unused.tcl:17: "cspm_file_add_remove_unicode
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:56: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:69: proz:startzconversiontests
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:101: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:104: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:119: preferences:backup_preferences
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:120: preferences:reset_for_benchmarking
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:121: preferences:deactivate_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:180: preferences:revert_preferences
/Users/leuschel/git_root/prob_prolog/tcl/benchmarks.tcl:181: preferences:activate_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:604: b_trace_checking:print_trace_as_fdr_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:927: analyze_hash_collisions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1004: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1006: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1092: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1099: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1101: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1106: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1108: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1111: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1113: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1115: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1117: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1636: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1638: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1717: get_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1732: preferences:clear_recent_documents 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2105: "preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2107: "eclipse_interface:ops_with_virtual_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2108: "eclipse_interface:ops_with_real_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2137: tcltk_mark_current_node_to_be_recomputed_wo_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2145: tcltk_mark_current_node_to_be_recomputed_with_random_enum
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2149: tcltk_finish_current_node_to_be_recomputed_with_random_enum
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2657: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2923: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3961: tcltk_clear_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4053: get_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4538: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4599: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4630: tcltk_clear_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:4675: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5638: tcltk_reset
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5643: tcltk_fast_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5838: tcltk_execute_trace_to_current_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5874: tcltk_find_shortest_trace_to_current_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5934: preferences:backup_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5973: get_preferences_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5990: preferences:revert_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5998: reset_to_defaults
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6012: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6013: get_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6040: get_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6072: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6076: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6078: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6494: tcltk_top_level_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6673: {Query
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6774: tcltk_analyse
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6828: tcltk_analyse_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6839: tcltk_show_typing_of_variables_and_constants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8121: tcltk_reset
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8448: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8630: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8716: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9074: count_errors_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9077: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9204: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9449: tcltk_cbc_refinement_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9461: tcltk_constraint_based_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9767: tcltk_get_options_dest_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9807: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10468: findall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10572: findall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13803: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13805: host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13810: get_preferences_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13926: prob_licence
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13953: prob_licence
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13984: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14024: mc_summary
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14040: symmetry_summary
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14475: "command_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14492: "command_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14932: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14994: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15002: "tcltk_turn_debugging_on
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15004: "tcltk_turn_debugging_off
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15007: "turn_on_run_time_type_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15009: "turn_off_run_time_type_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15012: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15013: "debug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15016: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15017: "nodebug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15049: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15083: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15110: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15689: "bmc_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15711: "kinduction_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15758: "ctigar_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15922: "reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15928: "reduce_graph_state_space:set_use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16010: reduce_graph_state_space:user_made_op_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16029: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16040: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16041: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16062: reduce_graph_state_space:user_made_arg_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16075: "reduce_graph_state_space:set_use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16705: tcltk_set_initial_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16716: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6402: tcltk_compute_coverage_and_enabling
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6405: tcltk_compute_coverage_and_degree
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6408: tcltk_compute_min_max
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6411: tcltk_get_vacuous_invariants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6416: tcltk_get_vacuous_guards
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6421: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6661: {Query
